/* fonts */
export const FontFamily = {
  interBold: "Inter-Bold",
  dongleBold: "Dongle-Bold",
  dongleRegular: "Dongle-Regular",
  dosisRegular: "Dosis-Regular",
  creteRoundRegular: "CreteRound-Regular",
  juliusSansOneRegular: "JuliusSansOne-Regular",
  interMedium: "Inter-Medium",
  judsonRegular: "Judson-Regular",
  interExtraBold: "Inter-ExtraBold",
  inriaSerifBold: "InriaSerif-Bold",
  inriaSerifRegular: "InriaSerif-Regular",
  interRegular: "Inter-Regular",
  interSemiBold: "Inter-SemiBold",
  inknutAntiquaBold: "InknutAntiqua-Bold",
  contentBold: "Content-Bold",
  latoLight: "Lato-Light",
  latoBold: "Lato-Bold",
  latoRegular: "Lato-Regular",
  latoBlack: "Lato-Black",
  rubikMedium: "Rubik-Medium",
  content: "Content",
};
/* font sizes */
export const FontSize = {
  size_xs: 12,
  size_xl: 20,
  size_5xl: 24,
  size_lg: 18,
  size_mini: 15,
  size_base: 16,
  size_sm: 14,
  size_smi: 13,
  size_3xs: 10,
  size_2xs: 11,
};
/* Colors */
export const Color = {
  colorWhite: "#fff",
  colorGray_100: "#928f8f",
  colorGray_200: "#8e7d7d",
  doctorPrimaryFont: "#011411",
  colorDimgray_100: "#6f6767",
  colorDimgray_200: "#636060",
  colorBlack: "#000",
  colorLightcyan_100: "#dbf5f1",
  colorLightcyan_200: "#d3f1ed",
  colorSeagreen: "#077547",
  colorPaleturquoise: "#b3ebe3",
  colorDarkblue: "#1c2aaf",
  colorDarkgray_100: "#9d9696",
  colorSnow_100: "#fff5f5",
  colorSnow_200: "#faf6f6",
  colorSnow_300: "#fbf4f4",
  colorBrown: "#ba1a4a",
  colorDarkcyan: "#2a9988",
  colorGainsboro_100: "#e4dbdb",
  colorGainsboro_200: "#d9d9d9",
  colorWhitesmoke: "#eeeaea",
  colorTeal_100: "#1f7769",
  colorDeepskyblue: "#35a9ea",
  colorMediumturquoise_100: "#85dbce",
  colorMediumturquoise_200: "#85dbcd",
  colorMediumturquoise_300: "rgba(133, 219, 206, 0.9)",
  colorRed: "#B61F1F",
};
/* border radiuses */
export const Border = {
  br_11xl: 30,
  br_101xl: 120,
  br_3xs: 10,
  br_5xs: 8,
  br_8xs: 5,
  br_6xs: 7,
  br_9981xl: 10000,
  br_xl: 20,
  br_9xs: 4,
  br_7xs: 6,
  br_xs: 12,
  br_5xs_6: 8,
};
